version: '2.2'

services:
  app:
    image: 'vasyl-test-project:latest'
    build:
      context: ..
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testtask?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      FLYWAY_URL: jdbc:mysql://db:3306/testtask?createDatabaseIfNotExist=true
      FLYWAY_SCHEMAS: testtask
      FLYWAY_USER: root
      FLYWAY_PASSWORD: mypass
      SPRING_PROFILES_ACTIVE: docker

  db:
    image: 'mariadb'
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: testtask